server:
  # 8004表示注册进zookeeper服务器的支付服务提供者端口
  port: 8004

spring:
  application:
    # 服务别名-- 注册进zookeeper的名称
    name: zookeeper-provider-payment
  cloud:
    zookeeper:
      # 默认localhost：2181
      connect-string: 106.15.37.47:2181