server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  # 添加链路监控  可在http://localhost:9411 查看服务间的调用链
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率值介于0到1 之间  1表示全部采集
      probability: 1
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb01?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 1qaz@WSX


##mybatis 配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.zl.springcloud.entities

##eureka客户端
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
       defaultZone: http://localhost:7001/eureka
      # 集群版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    # 访问路径可以显示ip地址
    prefer-ip-address: true